//get all receips
export const USERLOAD="USERLOAD"
export const GETRECIEPSUCCESS="GETRECIEPSUCCESS"
export const GETRECIEPFAILED="GETRECIEPFAILED"
//get one receip
// export const USERLOADING="USERLOADING"
export const GETONERECIEPSUCCESS="GETONERECIEPSUCCESS"
export const GETONERECIEPFAILED="GETONERECIEPFAILED"